site_name: EPS-MDS-2020-G2
site_description: Repositório da disciplina de EPS e MDS
repo_url: https://github.com/fga-eps-mds/EPS-2020-2-G2
site_dir: site
copyright: Copyright &copy; 2021, <a href="https://github.com/fga-eps-mds/EPS-2020-2-G2">EPS-MDS-2020-G2</a>.
theme:
  name: "material"
  logo: assets/img/logo.png
  favicon: assets/img/favicon.ico
  palette:
    primary: "white"

plugins:
  - search

extra_css:
  - assets/css/landing-page.css
  - assets/css/extra.css

extra_javascript:
  - assets/js/jquery.min.js
  - assets/js/jquery.zoom.min.js
  - assets/js/extra.js

lang:
  - "pt"

pages:
  - Home: "index.html"
  - Introdução: "intro.md"
  - Metodologia:
      - Templates:
          - Sprint Planning: "metodologia/templates/planning.md"
          - Sprint Review: "metodologia/templates/review.md"
          - Retrospectiva: "metodologia/templates/retrospective.md"
      - Gerenciamento de Riscos: "metodologia/gerenciaRisco.md"
  - Como contribuir:
      - Como Contribuir?: "contribuicao/contribuicao.md"
      - Código de Conduta: "contribuicao/conduta.md"
      - Testes no Front: "contribuicao/testes-front.md"
  - Reuniões:
      - 06/02:
          - Pauta: "reunioes/06-02/pauta.md"
          - Ata: "reunioes/06-02/ata.md"
          - Tarefas: "reunioes/06-02/tarefas.md"
      - 07/02:
          - Pauta: "reunioes/07-02/pauta.md"
          - Ata: "reunioes/07-02/ata.md"
      - 08/02:
          - Pauta: "reunioes/08-02/pauta.md"
          - Ata: "reunioes/08-02/ata.md"
  - Sprints:
      - Sprint 0:
          - Review: "sprints/0/review.md"
          - Retrospectiva: "sprints/0/retrospectiva.md"
      - Sprint 1:
          - Planning: "sprints/1/planning.md"
          - Review: "sprints/1/review.md"
          - Retrospectiva: "sprints/1/retrospectiva.md"
      - Sprint 2:
          - Planning: "sprints/2/planning.md"
          - Review: "sprints/2/review.md"
          - Retrospectiva: "sprints/2/retrospectiva.md"
      - Sprint 3:
          - Planning: "sprints/3/planning.md"
          - Review: "sprints/3/review.md"
          - Retrospectiva: "sprints/3/retrospectiva.md"
      - Sprint 4:
          - Planning: "sprints/4/planning.md"
  - Produto:
      - Documento de Visão: "produto/documento-visao.md"
      - Backlog do Produto: "produto/backlogProduto.md"
      - Identidade Visual: "produto/identidadevisual.md"
      - Protótipo: "produto/prototipo.md"
      - Lean inception: "produto/lean-inception.md"
      - Requisitos:
          - Requisitos questionário: "produto/requisitos/requisitosQuestionario.md"
          - Requisitos benchmarking: "produto/requisitos/benchmarking.md"
  - Projeto:
      - Termo de Abertura do Projeto: "projeto/tap.md"
      - Documento de Arquitetura: "projeto/documento-arquitetura.md"
      - Earned Value Management: "projeto/evm.md"